version: '3'
services:
  db:
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    container_name: coin_db
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    expose:
      - "5433"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: coin_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 2s
      retries: 3

  server:
    build:
      context: .
      dockerfile: ./docker/golang/Dockerfile
    container_name: coin_api
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/go/src/app
    ports:
      - "8081:8081"
    working_dir: /go/src/app
    command: "go run cmd/coin-api/main.go"
